# 1. SEMUA JALUR HTTP (80) DIALIKAN KE HTTPS (443)
server {
    listen 80;
    server_name sadewascoliving.cloud api.sadewascoliving.cloud;
    return 301 https://$host$request_uri;
}

# 2. JALUR FRONTEND (sadewascoliving.cloud) - HTTPS
server {
    listen 443 ssl;
    server_name sadewascoliving.cloud;

    ssl_certificate /etc/letsencrypt/live/sadewascoliving.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sadewascoliving.cloud/privkey.pem;

    location / {
        proxy_pass http://202.10.37.85:5173; # Nembak ke container frontend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 3. JALUR API (api.sadewascoliving.cloud) - HTTPS
server {
    listen 443 ssl;
    server_name api.sadewascoliving.cloud;

    ssl_certificate /etc/letsencrypt/live/api.sadewascoliving.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.sadewascoliving.cloud/privkey.pem;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}