name: Deploy to VPS

on:
  push:
    branches:
      - main # Robot akan bekerja setiap kali ada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Eksekusi perintah di VPS secara otomatis
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Masuk ke folder project yang sudah dipindah
            cd /home/sadewas_admin/SadewasHub
            
            # Tarik kode terbaru dari GitHub
            git pull origin main
            
            # Eksekusi docker tanpa sudo!
            docker compose exec -T app php artisan optimize